services:
  mysql:
    image: mysql:8.0
    container_name: prod_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: proyecto
      MYSQL_USER: userphp
      MYSQL_PASSWORD: passphp
    volumes:
      - ./db_data:/var/lib/mysql
      - ./dbinit.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - prod_net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  php:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: prod_php
    restart: always
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - prod_net

  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: prod_nginx
    restart: always
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    networks:
      - prod_net

volumes:
  db_data:

networks:
  prod_net:
    driver: bridge